language: python

python:
  - "3.7"
  - "3.8"

install:
  - sudo apt-get update
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p $HOME/miniconda
  - conda config --set always_yes yes
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels jboom
  - conda install vsearch
  - conda install caltha

script:
  - python3 -m pytest tests/
