language: python

python:
  - "3.7"

install:
  - sudo apt-get update
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes
  - conda update conda
  - conda info -a
  - conda config --add channels defaults
  - conda config --add channels anaconda
  - conda config --add channels bioconda
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION vsearch=2.14.2 pytest=5.4.1 setuptools=46.1.3 pandas=1.0.3
  - conda activate test-environment

script:
  - python3 -m pytest tests/
