{% set name = "caltha" %}
{% set version = "0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "43816e7545f679534b5c5c861868c170809e835b1f08801784bca1e01e86954b"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - pandas >=0.25.1
  run:
    - python
    - pandas >=0.25.1

about:
  home: "https://github.com/JasperBoom/caltha"
  license: "GNU Affero General Public v3"
  license_family: "AGPL"
  license_file: "../LICENSE.md"
  summary: "A python package to process UMI tagged mixed amplicon metabarcoding data."
  description: "NOTE: Caltha does require one more dependency which can not be installed
with this conda package. This dependency is VSEARCH, which can be installed using: conda install -c bioconda vsearch"
  dev_url: "https://github.com/JasperBoom/caltha/tree/master/src"
  doc_url: "https://jasperboom.github.io/caltha"
  doc_source_url: "https://github.com/JasperBoom/caltha/blob/master/docs/index.md"

extra:
  recipe-maintainers:
    - JasperBoom
