# Copyright (C) 2018 Jasper Boom (jboom@infernum.nl)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3 as 
# published by the Free Software Foundation.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

{% set name = "caltha" %}
{% set version = "0.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "c484373574513225ace7bab148b10e5ae1b508425b74eb4441edb62dfa4bedf7"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - pandas >=1.0.1
  run:
    - python
    - pandas >=1.0.1

about:
  home: "https://github.com/JasperBoom/caltha"
  license: "GNU Affero General Public v3"
  license_family: "AGPL"
  license_file: "../LICENSE.md"
  summary: "A python package to process UMI tagged mixed amplicon metabarcoding data."
  description: "Caltha requires one more dependency which can not be installed
with this conda package. This dependency is VSEARCH, which can be installed using: conda install -c bioconda vsearch"
  dev_url: "https://github.com/JasperBoom/caltha/tree/master/src"
  doc_url: "https://jasperboom.github.io/caltha"
  doc_source_url: "https://github.com/JasperBoom/caltha/tree/gh-pages"

extra:
  recipe-maintainers:
    - Jasper Boom
