{% set name = "caltha" %}
{% set version = "0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "88f83a1377635a85173904405fade5c06ab9f67e022be2397bc199be82f77362"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - pip
    - pandas >=0.25.1
  run:
    - python
    - pandas >=0.25.1

about:
  home: "https://github.com/JasperBoom/caltha"
  license: "GNU General Public v3 or later (GPLv3+)"
  license_family: "GPL3"
  license_file: "LICENSE"
  summary: "A python package to process UMI tagged mixed amplicon metabarcoding data."
  description: "NOTE: Caltha does require one more dependency which can not be installed
with this conda package. This dependency is VSEARCH, which can be installed using: conda install -c bioconda vsearch"
  dev_url: "https://github.com/JasperBoom/caltha"
  doc_url: "https://jasperboom.github.io/caltha"
  doc_source_url: "https://github.com/JasperBoom/caltha/blob/master/docs/index.md"

extra:
  recipe-maintainers:
    - JasperBoom
